version: '3.8'

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes  # Enable persistence
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  chroma:
    image: chromadb/chroma:0.6.3
    ports:
      - "${CHROMA_PORT}:8000"
    environment:
      - IS_PERSISTENT=TRUE
      - PERSIST_DIRECTORY=/chroma_data
      - ANONYMIZED_TELEMETRY=FALSE
    volumes:
      - ./chroma_data:/chroma_data
    env_file:
      - .env
      
volumes:
  redis_data: